inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'preservation-client.gemspec'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'lib/preservation/client/response_error_formatter.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/preservation/client.rb'

Style/WordArray:
  Enabled: false
