env:
  global:
    - CC_TEST_REPORTER_ID=47b57fbbf65654b17f33b6ff4a108ce2abed31a86468033f20eb4d4e9e09935a

dist: bionic
language: ruby
cache: bundler
rvm:
  - 2.5.3

env:
  - "RAILS_VERSION=5.2.3"
  - "RAILS_VERSION=6.0.0"

before_install: gem install bundler -v 2.0.2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
